### ISSUE TITLE
how does this work

### ISSUE THREAD

**Issue by shyamrao1514** [nur-zaman/isTheClassroomEmpty#4]
bro can you please provide a detailed information about the project else
give me your linked in profile

**Comment by nur-zaman** [comment]
I stopped updating it as I'm a bit busy rn. If you want to contribute/ keep this alive you can hit me up on discord.
my discord tag,  `.rnu`

**Comment by shyamrao1514** [comment]
can you send me the information about it like ppt presentation of it
like how does it work and functionalities

**Comment by nur-zaman** [comment]
I'm sorry can't help you with ppt. I'm closing the issue
